name: Node App

on: push

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker setup
        uses: docker/setup-docker-action@v4

      - name: Push to GHCR
        run: |          
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
          docker build -t --no-cache ghcr.io/${{ github.repository }}/node-app . 
          docker push ghcr.io/${{ github.repository }}/node-app
          
      - name: Trivy setup
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository }}/node-app
          format: table
          exit-code: 1
          ignore-unfixed: true
          cache: false
          severity: HIGH,CRITICAL